theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  
title: Think Machine The Last Week
description: Think Machine Module called The Last Week.
author: 
  name: Jorge Hortelano
  email: softwaremagico@gmail.com
